name: Test Python File

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run test.py
      run: |
        python -m pip install --upgrade pip
        pytest run tests/test.py --capture=no --exitfirst
    
